<a href="https://colab.research.google.com/github/TanujaMore27/Deep-Learning/blob/main/1_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand
torch.rand(2,3)

tensor([[0.0138, 0.5970, 0.0741],
        [0.0151, 0.1916, 0.3642]])

In [12]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways

#arange
print('using arange ->',torch.arange(0,10,2))

#using linspace
print('using linspace ->',torch.linspace(0,10,10))

# using eye
print('using eye ->',torch.eye(5))

# using full
print('using full ->',torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[214748364844, 219043332140, 188978561117],
        [223338299483, 227633266732, 231928234028]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

## Tensor Data Types

In [28]:
# find data tpye
x.dtype

torch.int64

In [30]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [32]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations
### 1. Scalar operation

In [34]:
x = torch.rand(2,2)
x

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [36]:
# add
x+2


tensor([[2.4440, 2.9478],
        [2.7445, 2.4892]])

In [37]:
# sub
x-1


tensor([[-0.5560, -0.0522],
        [-0.2555, -0.5108]])

In [38]:
# mul
x*3


tensor([[1.3321, 2.8435],
        [2.2335, 1.4676]])

In [39]:
# div
x/3


tensor([[0.1480, 0.3159],
        [0.2482, 0.1631]])

In [40]:
# int div
(x*100)//3


tensor([[14., 31.],
        [24., 16.]])

In [41]:
# mod
((x*100)//3)%2


tensor([[0., 1.],
        [0., 0.]])

In [42]:
# power
x**2

tensor([[0.1972, 0.8984],
        [0.5543, 0.2393]])

### 2. Element wise operation

In [43]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [44]:
# add
a + b


tensor([[0.2595, 0.9212, 1.4812],
        [0.9536, 0.9538, 1.3137]])

In [45]:
# sub
a - b


tensor([[ 0.2257,  0.4794, -0.4258],
        [-0.4592,  0.6280, -0.4667]])

In [46]:
# multiply
a * b


tensor([[0.0041, 0.1547, 0.5032],
        [0.1746, 0.1288, 0.3770]])

In [47]:
# division
a / b


tensor([[14.3533,  3.1705,  0.5534],
        [ 0.3499,  4.8557,  0.4757]])

In [48]:
# power
a ** b


tensor([[0.9763, 0.9243, 0.5436],
        [0.3726, 0.9625, 0.4654]])

In [49]:
# mod
a % b

tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

In [50]:
c = torch.tensor([1,-2,3,-4])

In [51]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [52]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [53]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [54]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [55]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [56]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [57]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [60]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 9., 8.],
        [9., 7., 9.]])

In [61]:
# sum
torch.sum(e)

tensor(47.)

In [62]:
# sum along columns
torch.sum(e,dim=0)

tensor([14., 16., 17.])

In [64]:
# sum along rows
torch.sum(e,dim=1)

tensor([22., 25.])

In [65]:
# mean
torch.mean(e)

tensor(7.8333)

In [66]:
# mean along col
torch.mean(e,dim=0)

tensor([7.0000, 8.0000, 8.5000])

In [67]:
# mean along rows
torch.mean(e,dim=1)

tensor([7.3333, 8.3333])

In [68]:
# median
torch.median(e)

tensor(8.)

In [69]:
# max
torch.max(e)

tensor(9.)

In [70]:
# min
torch.min(e)

tensor(5.)

In [72]:
# product
torch.prod(e)

tensor(204120.)

In [73]:
# standard deviation
torch.std(e)

tensor(1.6021)

In [74]:
# variance
torch.var(e)

tensor(2.5667)

In [75]:
# argmax
torch.argmax(e)

tensor(1)

In [76]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [77]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1],
        [5, 5],
        [0, 4]])


In [78]:
# matrix mul
torch.matmul(f,g)

tensor([[42, 60],
        [82, 59]])

In [79]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [80]:
# transpose
torch.transpose(f,0,1)

tensor([[2, 7],
        [6, 8],
        [7, 3]])

In [81]:
h = torch.randint(size=(3,3),low=0,high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [82]:
# determinant
torch.det(h)

tensor(-6.)

In [83]:
# inverse
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

### 5. Comparison operations

In [84]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [85]:
# greater than
i > j

tensor([[False,  True, False],
        [ True, False, False]])

In [87]:
# less than
i<j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [88]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [89]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [90]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[0., 4., 2.],
        [7., 1., 1.]])

In [91]:
# log
torch.log(k)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000]])

In [92]:
# exponential
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [93]:
# sqrt
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [94]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.8808],
        [0.9991, 0.7311, 0.7311]])

In [95]:
# softmax
torch.softmax(k,dim=0)

tensor([[9.1105e-04, 9.5257e-01, 7.3106e-01],
        [9.9909e-01, 4.7426e-02, 2.6894e-01]])

In [96]:
# relu
torch.relu(k)

tensor([[0., 4., 2.],
        [7., 1., 1.]])

### Inplace Operations

In [97]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [98]:
m.add_(n)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [99]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [100]:
n

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [101]:
torch.relu(m)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [102]:
m.relu()

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

### Copying a Tensor

In [103]:
a = torch.rand(2,3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [104]:
b=a

In [105]:
b

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [106]:
a[0][0]=0

In [107]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [108]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [109]:
id(a)

140473147605072

In [110]:
id(b)

140473147605072

In [111]:
b = a.clone()

In [112]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [113]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [114]:
a[0][1] = 1

In [115]:
a

tensor([[0.0000, 1.0000, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [116]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [117]:
id(a)

140473147605072

In [118]:
id(b)

140473149067888